slqx migration, credential processing and cookie authentication
AaronErhardt/Triox pull request #34
Opened 2021-07-06 12:58 UTC by realaravinth

This PR is massive and I apologize for that. The `sqlx` migration work touched various areas so I figured I'd refactor those areas as well.

## Changes:
- `sqlx` migration
- credential processing with [argon2-creds](https://github.com/realaravinth/argon2-creds)
- `jwt` to cookie-based authentication based

2021-07-06 13:55 UTC, AaronErhardt commented
Wow, that's huge! Thank you so much for your work!
I have an exam tomorrow so I don't have time today, but I will review these patches after the exam :)

2021-07-06 14:11 UTC, realaravinth commented
sure, take your time! and best of luck for the test! :)

2021-07-07 19:54 UTC, AaronErhardt requested changes
That was quite a lot to review but looks pretty good overall! There were just a few minor things that need to be adjusted.

2021-07-07 19:54 UTC, AaronErhardt commented on src/apps/files/upload.rs
> +                }
I guess this is another place where cap-std could be useful...

2021-07-07 19:54 UTC, AaronErhardt commented on src/tests/helpers.rs
> +            //.insert_header((header::CONTENT_TYPE, "application/json"))
I guess the commented line here can be removed

2021-07-07 20:38 UTC, AaronErhardt commented
Also I just noticed that if no Postgres server is running, the connection timeout is pretty high which causes the program to run for quite some time before realizing that there's no server to connect to. Also in this phase while waiting for the database pool (which should be pretty much idle) the server has a pretty high CPU usage for some reason...

2021-07-07 21:18 UTC, AaronErhardt commented on src/apps/files/mod.rs
> +            username, query_path
I just checked and it seems like this isn't possible but the server responds with "username_case_mapped violation". So it seems that argon2-creds with case mapping solves this issue. Still cap-std could improve the robustness of the code.

2021-07-08 04:26 UTC, realaravinth commented on src/app_state.rs
> +        });
`argon2-creds` uses lazily initialized regex filters, they are large and take time to initialize. By calling `init`, we are initializing at startup where we can afford a little delay.  

And no, it isn't lost. Regex filters are `static` and `arong2-creds` has handles to them at all times.

2021-07-08 04:28 UTC, realaravinth commented on src/api/v1/auth.rs
> +        //        .append_header((header::LOCATION, "/login"))
That's `actix-web` v4 stuff. We will be migrating to v4 soon

2021-07-08 04:32 UTC, realaravinth commented on Cargo.toml
> +my-codegen = {package = "actix-web-codegen", git ="https://github.com/realaravinth/actix-web"}
Two reasons:
- main actox-web-codegen doesn't take `expr` for route. IMO, having `expr` for route is nice as you can save route in a `const` and use it everywhere (tests, templates, etc)
- this is more of an after thought: I'm thinking about moving `src/tests/helper.rs` into the same crate.

2021-07-08 04:34 UTC, realaravinth commented on src/api/v1/account/delete.rs
> +    id.forget();
Ah, good catch!

2021-07-08 04:37 UTC, realaravinth commented on src/api/v1/auth.rs
> +            let email_fut = sqlx::query_as!(
Good catch! It's baggage from previous iterations, I'll be sure to clean it up.

2021-07-08 04:38 UTC, realaravinth commented on src/api/v1/auth.rs
> +        //  }
I was going to make a PR for the same :)

2021-07-08 04:40 UTC, realaravinth commented on src/apps/files/mod.rs
> +            username, query_path
You are right about argon2-creds`, it does username case mapped validation. 

`cap-std` looks cool but that is for another PR and it requires serious thought. We should also look into implement some access control model

2021-07-08 04:41 UTC, realaravinth commented on src/apps/files/upload.rs
> +                }
[Please see previous comment](https://github.com/AaronErhardt/Triox/pull/34#discussion_r665864354)

2021-07-08 04:41 UTC, realaravinth commented on src/tests/helpers.rs
> +            //.insert_header((header::CONTENT_TYPE, "application/json"))
That's actix-web v4 stuff

2021-07-08 04:45 UTC, realaravinth commented
IMO, the timeout is alright as it comes in handy when theres a start up delay in situations like systemd service set to launch thus program at boot time or launching a trail net with docker compose. 

The high CPU usage is caused by `argon2-creds` initializing regex filters. In release builds, it should be brief but in debug, it's awfully long.

2021-07-08 07:05 UTC, AaronErhardt commented on Cargo.toml
> +my-codegen = {package = "actix-web-codegen", git ="https://github.com/realaravinth/actix-web"}
Makes sense. Do plan to upstream these features?

2021-07-08 07:08 UTC, realaravinth commented on Cargo.toml
> +my-codegen = {package = "actix-web-codegen", git ="https://github.com/realaravinth/actix-web"}
I did but there wasn't enough response to warrant inclusion into the main lib. See [#2216](https://github.com/actix/actix-web/pull/2216). The fork will be maintained and publish to crates.io.

2021-07-08 07:17 UTC, AaronErhardt commented on src/apps/files/mod.rs
> +            username, query_path
I agree there needs to be a more sophisticated method for handling files. Btw. I still plan on implementing some sort of encrypted federated block storage that can easily be synced. I already started with a FUSE file system implementation but it's still far from finished. Maybe I will find more time for it in a few weeks...

2021-07-08 07:34 UTC, realaravinth commented
I've added a coverage workflow. Tarpaulin is failing on my computer with same error(broken pipe) but it seems to function well in CI runs on my other repositories. We'll see if I can get it running on here.

2021-07-08 07:40 UTC, realaravinth commented on src/apps/files/mod.rs
> +            username, query_path
I've been thinking about a block based implementation as well. We'll approach things step by step, this way it'll give us room to experiment and pick methods that work best for us. For now(as in this PR), this seems adequate. 

I want to resolve access control issues with web UI before implementing files backend and its access control mechanisms. Currently, unauthorized access is possible for `/static/files.html`. It won't list files any users but it's possible to view the webpage.

2021-07-08 07:52 UTC, AaronErhardt approved these changes
Looks good to me! I think we can merge the PR now.

2021-07-08 08:01 UTC, merged